package com.sdjpa.sdjpa;

import com.github.javafaker.Faker;
import com.sdjpa.sdjpa.entity.Student;
import com.sdjpa.sdjpa.repository.StudentRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.domain.Sort;

@Configuration
public class StudentConfiguration {
   @Bean
    CommandLineRunner commandLineRunner(StudentRepository studentRepository){
        return args -> {
            System.out.println("strating App");
            autoGeneratedStudent(studentRepository);
        };
    }
    
    private void autoGeneratedStudent(StudentRepository studentRepository){
        Faker faker = new Faker();
        for (int i=0;i<20;i++){
            String first_name = faker.name().firstName();
            String last_name = faker.name().lastName();
            int age = faker.number().numberBetween(17, 30);
            String email = String.format("%s%s@gmail.com", first_name, last_name);
            String num_telephone = faker.phoneNumber().cellPhone();
            Student student = new Student(
                    null,
                    first_name,
                    last_name,
                    age,
                    email,
                    num_telephone
            );
            studentRepository.save(student);
        }
    }
}
